CREATE TABLE IF NOT EXISTS training_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    duration_in_hours INTEGER NOT NULL,
    level VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_training_courses_active ON training_courses(active);
CREATE INDEX idx_training_courses_title ON training_courses(title);
CREATE INDEX idx_training_courses_level ON training_courses(level);
CREATE INDEX idx_training_courses_price ON training_courses(price);
CREATE INDEX idx_training_courses_active_title ON training_courses(active, title);